#cloud-config

# Hostname management
preserve_hostname: False
hostname: {{HOSTNAME}}
fqdn: {{HOSTNAME}}.example.local

mounts:
 - [ kubernetes_tag, /kubernetes, 9p, "trans=virtio,version=9p2000.L,nofail", "0", "0" ]

# Remove cloud-init when finished with it
runcmd:
  - [ docker, load, -i, /kubernetes/kube-apiserver.tar ]
  - [ docker, load, -i, /kubernetes/kube-controller-manager.tar ]
  - [ docker, load, -i, /kubernetes/kube-proxy.tar ]
  - [ docker, load, -i, /kubernetes/kube-scheduler.tar ]
  - [ dpkg, -i, /kubernetes/debs_backup/cri-tools.deb, /kubernetes/debs_backup/kubeadm.deb, /kubernetes/debs_backup/kubectl.deb, /kubernetes/debs_backup/kubelet.deb, /kubernetes/debs_backup/kubernetes-cni.deb ]
  - [ touch, /all_is_done ]

# Configure where output will go
output:
  all: ">> /var/log/cloud-init.log"

# configure interaction with ssh server
ssh_svcname: ssh
ssh_deletekeys: True
ssh_genkeytypes: ['rsa', 'ecdsa']

# Install my public ssh key to the first user-defined user configured
# in cloud.cfg in the template (which is centos for CentOS cloud images)
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmdX7VspleP6fn3TQjKLKY/BKeQ68edEdRAUJG07A6FoFhYzTjknK4vx9nVRlkSQ68sbhcNgdutKdis6VN5yPO7WivGXuoXkaa6TAAtfmoYhPkPXfAphwOHsge/NrMBxkVUilmsKjDJWb75OtlKJ1ZhM58B18ipb+1Pk2ktdsCpDZrdg++bR+OQjl2SRjerr7BwdMGouTt0jplrs34aOnvINMQ4O8kub07rp3Fjy1RtAkUkxWUynZ+/cKIl/h8MOokxOP6LKtxcvIjCIuZAPtnquQuLdPj9yF7O5ubFEgKqYiRm3zctJYMRFQeHOY4snmFT5Rz7HK6LFv1tt96eqrX rojkov@desktop
